### ISSUE TITLE
w example still incorrect

### ISSUE THREAD

**Issue by LeventErkok** [mikeizbicki/HerbiePlugin#17]
[This is the same as https://github.com/mikeizbicki/HerbiePlugin/issues/11, but github doesn't let me open closed issues.]

I'm still getting an incorrect output for the `w` example. I just pulled from github and did a fresh-make. To wit:

```
w :: Double -> Double -> Double
w far near = -(2 * far * near) / (far - near)
```

Herbie says:

```
Compiling with Herbie floating point stabilization
Found math expression within binding w :: Double -> Double -> Double
  original expression = (2 * far_amS * near_amT) / (far_amS - near_amT)
  improved expression = if far_amS < (negate 1.7210442634149447e81)
    then (far_amS / (far_amS - near_amT)) * 2 * near_amT
    else if far_amS < 8.364504563556443e16
        then (far_amS * 2) / (far_amS - near_amT) / near_amT
        else (far_amS / (far_amS - near_amT)) * 2 * near_amT
  original error = 13.82279321294945 bits
  improved error = 2.34375e-2 bits
  WARNING: Not substituting the improved expression into your code
  WARNING: Cannot satisfy the constraint: Fractional Double
```

The "renaming" of variables is a bit annoying, but no big deal.

But those expressions are still vastly different. Based on this, I defined: (Note the extra wrapping of negation to match the original; Herbie matches the subexpression only.)

```
w' :: Double -> Double -> Double
w' far near = -(if far < (negate 1.7210442634149447e81)
    then (far / (far - near)) * 2 * near
        else if far < 8.364504563556443e16
                then (far * 2) / (far - near) / near
                else (far / (far - near)) * 2 * near)
```

Just try it on some simple values:

```
*T> w 3 4
24.0
*T> w' 3 4
1.5
```

At least one issue is that the second `then` clause still needs to be:

```
   ((far * 2) / (far - near)) * near
```

There might be other issues as well, of course.

**Comment by mikeizbicki** [comment]
Thanks for following through with this.  There was another bug :)  This one didn't affect the actual expression Herbie outputs into core, it only affects the way it gets printed to the screen (which is why I didn't see it).

The problem was that parenthesis were not being displayed correctly.
```
(far * 2) / (far - near) / near
```
Should have read
```
(far * 2) / ((far - near) / near)
```
Which gives the correct answer.

-----

I introduced the unique tags (`_asd` thing) when I fixed issue #8 caused by name clashes. I've figured out a way to remove the tags from variables that don't need them (I think).  So the output should look pretty again.

----

Thanks again for all the bug reports.  I really appreciate it :)
